#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: DEBUG
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///ittest
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate

  security:
    oauth2:
      client:
        provider:
          active-directory:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          active-directory:
            client-id: the-client-id
            client-secret: the-client-secret
integration:
  active-directory:
    url: http://localhost:${wiremock.server.port:}/api-active-directory
