#========================================
# General settings
#========================================
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: access-mapper
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          active-directory:
            authorization-grant-type: client_credentials
            provider: active-directory

integration:
  active-directory:
    connectTimeout: 5
    readTimeout: 30

resilience4j:
  circuitbreaker:
    instances:
      active-directory:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
