#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: DEBUG

spring:
  cache:
    type: none
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///junittest
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          active-directory:
            token-uri: http://token.url
        registration:
          active-directory:
            client-id: the-client-id
            client-secret: the-client-secret
